themes:
  basic:
    path: basictheme.schematic
    blocks_infrontof_spawn: 8
    permission: realm.theme.other
    item:
      name: '&eBasic Theme'
      material: GRASS
      durability: 1
      lore:
        - '§7The theme of the basic island'
config:
  #The space beetween each realm
  spacing: 500
  #The world where realms will be created
  world: AdvancedRealmWorld
  spawn:
    world: world
    x: -1
    y: 66
    z: -1
    yaw: 0
    pitch: 0
#Configure the percentage for the ore generator. ⚠️ The total percentage must be equal to 100 !
ore_generator:
  activated: true
  cobblestone: 73
  stone: 0
  coal_ore: 7
  iron_ore: 6
  lapis_ore: 2
  redstone_ore: 5
  gold_ore: 4
  emerald_ore: 2
  diamond_ore: 1

vote:
  #Cooldown is handled like that "days/hours/minutes/seconds"
  cooldown: "0d/7h/0m/0s"
  #people can vote multiple times for the same realm
  multiplevote: false
  #people can vote for their own realm
  ownedvote: false
