name: AdvancedRealm
author: iPazu
version: 1.2
main: fr.ipazu.advancedrealm.Main
commands:
  unclaim:
  claim:
  realm:
  home:
  visit:
  configrealm:
depends: [SmartInvs,WorldEdit]
softdepend: [PlaceholderAPI]